default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: day10_development

test:
  <<: *default
  database: day10_test

production:
  <<: *default
  database: day10_production
  username: day10
  password: <%= ENV['DAY10_DATABASE_PASSWORD'] %>
